import 'angular';
import 'angular-ui-router';
import 'angular-animate';
import 'angular-breadcrumb';
import 'angular-sanitize';
import 'prismjs';
import 'jquery';
import 'ngSmoothScroll';
import 'ng-clamp';